version: '3'

services:

  mysql:
    image: mysql:5.7
    # restart: always  # 重启系统后重启容器
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # 只在数据库未初始化的情况下有效
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

  adminer:  # 数据库管理
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis:5
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DATA_DIR}/data:/data  # 数据存储在 /data 下